-- MySQL Script generated by MySQL Workbench
-- Mon Nov  1 19:59:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nacionalidad` (
  `idNacionalidad` INT NOT NULL AUTO_INCREMENT,
  `Nacionalidadcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNacionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `Departamentocol` VARCHAR(45) NOT NULL,
  `id_Nacionalidad` INT NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  CONSTRAINT `nacionalidad`
    FOREIGN KEY (`id_Nacionalidad`)
    REFERENCES `mydb`.`Nacionalidad` (`idNacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `nacionalidad_idx` ON `mydb`.`Departamento` (`id_Nacionalidad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `Municipio` VARCHAR(100) NOT NULL,
  `idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  CONSTRAINT `departamento`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `departamento_idx` ON `mydb`.`Municipio` (`idDepartamento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(10) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `edad` INT NOT NULL,
  `celular` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `municipio` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  CONSTRAINT `municipio`
    FOREIGN KEY (`municipio`)
    REFERENCES `mydb`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `municipio_idx` ON `mydb`.`Persona` (`municipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pasajeros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pasajeros` (
  `idPasajeros` INT NOT NULL AUTO_INCREMENT,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idPasajeros`),
  CONSTRAINT `persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `persona_idx` ON `mydb`.`Pasajeros` (`idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `idPersona` INT NOT NULL,
  `idCargo` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  CONSTRAINT `persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cargo`
    FOREIGN KEY (`idCargo`)
    REFERENCES `mydb`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `persona_idx` ON `mydb`.`Empleado` (`idPersona` ASC) VISIBLE;

CREATE INDEX `cargo_idx` ON `mydb`.`Empleado` (`idCargo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avion` (
  `idAvion` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT NOT NULL,
  `piloto` INT NOT NULL,
  `copiloto` INT NOT NULL,
  PRIMARY KEY (`idAvion`),
  CONSTRAINT `empleado1`
    FOREIGN KEY (`piloto`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empleado2`
    FOREIGN KEY (`copiloto`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `empleado1_idx` ON `mydb`.`Avion` (`piloto` ASC) VISIBLE;

CREATE INDEX `empleado2_idx` ON `mydb`.`Avion` (`copiloto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ruta` (
  `idRuta` INT NOT NULL AUTO_INCREMENT,
  `origen` INT NOT NULL,
  `destino` INT NOT NULL,
  `valor` DECIMAL NOT NULL,
  PRIMARY KEY (`idRuta`),
  CONSTRAINT `origen`
    FOREIGN KEY (`origen`)
    REFERENCES `mydb`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `destino`
    FOREIGN KEY (`destino`)
    REFERENCES `mydb`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `origen_idx` ON `mydb`.`Ruta` (`origen` ASC) VISIBLE;

CREATE INDEX `destino_idx` ON `mydb`.`Ruta` (`destino` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`vuelo_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vuelo_estado` (
  `idvuelo_estado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvuelo_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vuelos` (
  `idVuelo` INT NOT NULL AUTO_INCREMENT,
  `idAvion` INT NOT NULL,
  `ruta` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idVuelo`),
  CONSTRAINT `avion`
    FOREIGN KEY (`idAvion`)
    REFERENCES `mydb`.`Avion` (`idAvion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ruta`
    FOREIGN KEY (`ruta`)
    REFERENCES `mydb`.`Ruta` (`idRuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estado`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`vuelo_estado` (`idvuelo_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `avion_idx` ON `mydb`.`Vuelos` (`idAvion` ASC) VISIBLE;

CREATE INDEX `ruta_idx` ON `mydb`.`Vuelos` (`ruta` ASC) VISIBLE;

CREATE INDEX `estado_idx` ON `mydb`.`Vuelos` (`estado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pasajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pasajes` (
  `idPasajes` INT NOT NULL AUTO_INCREMENT,
  `idPasajero` INT NOT NULL,
  `idVuelo` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `asiento` INT NOT NULL,
  PRIMARY KEY (`idPasajes`),
  CONSTRAINT `pasajero`
    FOREIGN KEY (`idPasajero`)
    REFERENCES `mydb`.`Pasajeros` (`idPasajeros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vuelo`
    FOREIGN KEY (`idVuelo`)
    REFERENCES `mydb`.`Vuelos` (`idVuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `pasajero_idx` ON `mydb`.`Pasajes` (`idPasajero` ASC) VISIBLE;

CREATE INDEX `vuelo_idx` ON `mydb`.`Pasajes` (`idVuelo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`pasajeros_vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pasajeros_vuelo` (
  `idpasajeros_vuelo` INT NOT NULL AUTO_INCREMENT,
  `idVuelo` INT NOT NULL,
  `idPasajero` INT NOT NULL,
  PRIMARY KEY (`idpasajeros_vuelo`),
  CONSTRAINT `vuelo`
    FOREIGN KEY (`idVuelo`)
    REFERENCES `mydb`.`Vuelos` (`idVuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pasajero`
    FOREIGN KEY (`idPasajero`)
    REFERENCES `mydb`.`Pasajeros` (`idPasajeros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `vuelo_idx` ON `mydb`.`pasajeros_vuelo` (`idVuelo` ASC) VISIBLE;

CREATE INDEX `pasajero_idx` ON `mydb`.`pasajeros_vuelo` (`idPasajero` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`profesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesion` (
  `idprofesion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idprofesion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesion_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesion_empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `idProfesion` INT NOT NULL,
  CONSTRAINT `empleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `profesion`
    FOREIGN KEY (`idProfesion`)
    REFERENCES `mydb`.`profesion` (`idprofesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `empleado_idx` ON `mydb`.`profesion_empleado` (`idEmpleado` ASC) VISIBLE;

CREATE INDEX `profesion_idx` ON `mydb`.`profesion_empleado` (`idProfesion` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SELECT * FROM Vuelos;
